exclude: [gulpfile.js, package.json, node_modules, Gemfile, Gemfile.lock]
baseurl: /archiparti
permalink: /:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  - questions
