exclude: [gulpfile.js, package.json, node_modules, Gemfile, Gemfile.lock]
baseurl: /archiparti
permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news-item"
      permalink: /news/:year-:month-:day-:title.html

collections:
  - questions
